# Generated by Django 4.2.7 on 2026-08-09 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст ответа')),
                ('answer_type', models.CharField(choices=[('single', 'Одиночный выбор'), ('multiple', 'Множественный выбор')], default='single', max_length=10, verbose_name='Тип ответа')),
                ('intermediate_text', models.TextField(help_text='Показывается пользователю сразу после выбора ответа', verbose_name='Промежуточная консультация')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_final', models.BooleanField(default=False, verbose_name='Финальный ответ (ведет к выводу)')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Conclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Номер вывода')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('short_text', models.TextField(verbose_name='Краткий вывод (бесплатно)')),
                ('full_text', models.TextField(verbose_name='Итоговый вывод (платно)')),
                ('pros', models.TextField(blank=True, help_text='Положительные аспекты для пользователя', verbose_name='Плюсы ситуации')),
                ('cons', models.TextField(blank=True, help_text='Негативные аспекты для пользователя', verbose_name='Минусы ситуации')),
                ('success_rate', models.IntegerField(default=50, help_text='От 0 до 100%', verbose_name='Вероятность успеха')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('documents', models.FileField(blank=True, help_text='Прикрепите файлы документов', null=True, upload_to='docs/%Y/%m/%d/', verbose_name='Документы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Вывод',
                'verbose_name_plural': 'Выводы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LegalDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название направления')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка (CSS класс)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Юридическое направление',
                'verbose_name_plural': 'Юридические направления',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Порядковый номер')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('help_text', models.TextField(blank=True, help_text='Дополнительная информация к вопросу', verbose_name='Подсказка')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название опросника')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='core.legaldirection', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Опросник',
                'verbose_name_plural': 'Опросники',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='Ключ сессии')),
                ('answers_history', models.JSONField(default=list, verbose_name='История ответов')),
                ('completed', models.BooleanField(default=False, verbose_name='Завершен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('conclusion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.conclusion', verbose_name='Полученный вывод')),
                ('current_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.question', verbose_name='Текущий вопрос')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.questionnaire', verbose_name='Опросник')),
            ],
            options={
                'verbose_name': 'Сессия пользователя',
                'verbose_name_plural': 'Сессии пользователей',
                'unique_together': {('session_key', 'questionnaire')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.questionnaire', verbose_name='Опросник'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('paid', 'Оплачено'), ('failed', 'Ошибка'), ('refunded', 'Возврат')], default='pending', max_length=10, verbose_name='Статус')),
                ('payment_id', models.CharField(blank=True, max_length=100, verbose_name='ID платежа')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email для отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('conclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conclusion', verbose_name='Вывод')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.usersession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='conclusion',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusions', to='core.questionnaire', verbose_name='Опросник'),
        ),
        migrations.CreateModel(
            name='AnswerConclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conclusion_link', to='core.answer', verbose_name='Ответ')),
                ('conclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_links', to='core.conclusion', verbose_name='Вывод')),
            ],
            options={
                'verbose_name': 'Связь ответа с выводом',
                'verbose_name_plural': 'Связи ответов с выводами',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_answers', to='core.question', verbose_name='Следующий вопрос'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.question', verbose_name='Вопрос'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('questionnaire', 'order')},
        ),
    ]
