# Generated by Django 4.2.7 on 2026-08-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conclusion',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Только платно'),
        ),
        migrations.AddField(
            model_name='conclusion',
            name='purchases_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Покупок'),
        ),
        migrations.AddField(
            model_name='conclusion',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотров'),
        ),
        migrations.AddField(
            model_name='legaldirection',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='completions_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Завершений'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотров'),
        ),
    ]
