# Generated by Django 4.2.7 on 2026-08-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_conclusion_is_paid_conclusion_purchases_count_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersession',
            unique_together=set(),
        ),
    ]
