# Generated by Django 4.2.7 on 2026-08-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usersession_unique_together'),
    ]

    operations = [
    ]
