# Generated by Django 4.2.7 on 2026-08-13 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_unique_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.usersession', verbose_name='Сессия'),
        ),
    ]
