# Generated by Django 4.2.7 on 2026-08-13 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_payment_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('template_type', models.CharField(choices=[('claim', 'Исковое заявление'), ('complaint', 'Жалоба'), ('petition', 'Ходатайство'), ('statement', 'Заявление'), ('agreement', 'Соглашение'), ('objection', 'Возражение'), ('appeal', 'Апелляционная жалоба'), ('letter', 'Письмо'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип документа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('html_template', models.TextField(help_text='Используйте {{ full_name }}, {{ address }}, {{ phone }}, {{ email }} и другие переменные', verbose_name='HTML шаблон')),
                ('css_styles', models.TextField(blank=True, default='\n        body { font-family: Arial, sans-serif; font-size: 12pt; margin: 40px; }\n        h1 { color: #1a1a2e; font-size: 18pt; text-align: center; }\n        .header { text-align: right; margin-bottom: 30px; }\n        .content { line-height: 1.6; }\n        .footer { margin-top: 50px; text-align: right; }\n        .signature { margin-top: 30px; }\n        .variable { color: #007bff; background: #f0f0f0; padding: 2px 5px; border-radius: 3px; }\n    ', verbose_name='CSS стили')),
                ('variables', models.JSONField(default=list, help_text='Список переменных, например: ["full_name", "address", "phone"]', verbose_name='Переменные')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('conclusion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='core.conclusion', verbose_name='Вывод')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_data', models.JSONField(default=dict, verbose_name='Данные пользователя')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='documents/pdfs/%Y/%m/%d/', verbose_name='PDF файл')),
                ('content_text', models.TextField(blank=True, verbose_name='Текст документа')),
                ('status', models.CharField(choices=[('pending', 'В процессе'), ('ready', 'Готов'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата скачивания')),
                ('conclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conclusion', verbose_name='Вывод')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.documenttemplate', verbose_name='Шаблон')),
                ('user_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.usersession', verbose_name='Сессия пользователя')),
            ],
            options={
                'verbose_name': 'Сгенерированный документ',
                'verbose_name_plural': 'Сгенерированные документы',
                'ordering': ['-created_at'],
            },
        ),
    ]
