# Generated by Django 4.2.7 on 2026-08-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_documenttemplate_generateddocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название правила')),
                ('rule_type', models.CharField(choices=[('questionnaire', 'Генерация опросников'), ('consultation', 'Генерация консультаций'), ('document', 'Генерация документов'), ('conclusion', 'Генерация выводов'), ('general', 'Общие правила')], default='general', max_length=20, verbose_name='Тип правила')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('rules_text', models.TextField(help_text='Инструкция для AI. Используйте {{ topic }}, {{ category }} для подстановки', verbose_name='Свод правил')),
                ('prompt_template', models.TextField(blank=True, help_text='Шаблон запроса к AI. Используйте {{ rules }} для вставки правил, {{ topic }} для темы', verbose_name='Шаблон промпта')),
                ('examples', models.JSONField(blank=True, default=list, help_text='Примеры для обучения AI (few-shot)', verbose_name='Примеры')),
                ('variables', models.JSONField(blank=True, default=list, verbose_name='Переменные')),
                ('priority', models.IntegerField(default=0, verbose_name='Приоритет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Правило для AI',
                'verbose_name_plural': 'Правила для AI',
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
