# Generated by Django 4.2.7 on 2026-08-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_airules'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='workflow',
            field=models.JSONField(blank=True, default=dict, verbose_name='Визуальный алгоритм'),
        ),
    ]
