# Generated by Django 4.2.7 on 2026-08-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_questionnaire_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='conclusion',
            name='user_data_fields',
            field=models.JSONField(blank=True, default=list, help_text='Список полей, которые нужно заполнить пользователю. Формат: [{"name": "full_name", "label": "ФИО", "type": "text", "required": true}]', verbose_name='Поля для сбора данных'),
        ),
    ]
