# Generated by Django 4.2.7 on 2026-09-28 10:07

import django.core.validators
import core.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customer_accounts_and_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConclusionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('docx_file', models.FileField(storage=core.storage.ProtectedDocumentStorage(), upload_to='protected/documents/docx/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['docx'])], verbose_name='Файл DOCX')),
                ('pdf_file', models.FileField(storage=core.storage.ProtectedDocumentStorage(), upload_to='protected/documents/pdf/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Файл PDF')),
                ('is_active', models.BooleanField(default=True, verbose_name='Выдавать пользователю')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('conclusion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_documents', to='core.conclusion', verbose_name='Вывод')),
            ],
            options={
                'verbose_name': 'Комплект DOCX + PDF',
                'verbose_name_plural': 'Комплекты DOCX + PDF',
                'ordering': ['conclusion__order', 'title'],
            },
        ),
    ]
